name: medoc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  arcore_flutter_plugin: ^0.0.11
  translator: ^0.1.7
  http: ^0.13.4
  html: ^0.15.0
  device_preview: ^1.0.0
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.7
  google_fonts: ^2.3.1
  flutter_mobile_vision: ^0.1.4+1
  text_to_speech: ^0.2.3
  camera: ^0.9.4+14
  image_picker: ^0.8.4+9
  video_player: ^2.2.18
  video_player_web: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

